### ISSUE TITLE
Docs: Link to Control.Debounce is broken on Hackage

### ISSUE THREAD

**Issue by pmiddend** [debug-ito/fold-debounce#3]
To see it, go to [Control.FoldDebounce](https://hackage.haskell.org/package/fold-debounce-0.2.0.13/docs/Control-FoldDebounce.html) and try to click the link `Control.Debounce`. It links to https://hackage.haskell.org/package/fold-debounce-0.2.0.13/docs/Control-Debounce.html which doesn't exist. Maybe use a normal hyperlink instead of a Haskell-Link here?

**Comment by debug-ito** [comment]
Thanks for reporting! I used Haskell-links, but haddock just doesn't know where the Control.Debounce is. I'll fix it...

**Comment by debug-ito** [comment]
I updated the doc in 0.2.0.14.
